### ISSUE TITLE
CPPDEBUG flag for deployment

### ISSUE THREAD

**Issue by arcondello** [dwavesystems/minorminer#1]
I disabled CPPDEBUG flag conditional in deploy because travis was throwing an error:

Worker information
/Users/travis/.travis/job_stages: line 599: conditional binary operator expected
/Users/travis/.travis/job_stages: line 599: expected `)'
/Users/travis/.travis/job_stages: line 599: syntax error near `$CPPDEBUG)'
/Users/travis/.travis/job_stages: line 599: `  if [[ (-v $CPPDEBUG) && ("$TRAVIS_TAG" != "") ]]; then'

I believe that it was serving a purpose and should be reactivated.

Additionally, the linux builds were failing because they were expecting the flag and not seeing it.

**Comment by bellert** [comment]
Fixed by PR #14
