### ISSUE TITLE
Python interface documentation missing 

### ISSUE THREAD

**Issue by JoelPasvolsky** [dwavesystems/minorminer#102]
**Description**
![image](https://user-images.githubusercontent.com/34041130/73499953-5d601000-4376-11ea-8ae5-42b46eb60f84.png)

**To Reproduce**
Take a look

**Expected behavior**
In the past the Python interface was documented here

**Environment:**
 - OS: [Ubuntu 16.04.4 LTS]
 - Python version: [e.g. 3.7.0]

**Additional context**
I'm hopeful unified docs in the SDK solves this

**Comment by JoelPasvolsky** [comment]
WORKAROUND: for now users can see Python IF in the SDK docs, https://docs.ocean.dwavesys.com/en/latest/docs_minorminer/source/reference/pythondocs.html.

(Need to get the C interface working there still.)

**Comment by arcondello** [comment]
We will also need to update minorminer to use a newer sphinx, blocks https://github.com/dwavesystems/dwave-ocean-sdk/issues/43
