### ISSUE TITLE
Cache issues with embedding K8 onto Leap Advantage graph

### ISSUE THREAD

**Issue by hmunozb** [dwavesystems/minorminer#162]
**Description**
find_clique_embedding does not successfully return for the graph of Advantage_system1.1 with `use_cache=True`
This behavior affects `dwave.system.samplers.DWaveCliqueSampler`

**To Reproduce**
Minimum example (for K8) assuming configuration for Advantage_system1.1

```python
from dimod import BinaryQuadraticModel
from minorminer.busclique import find_clique_embedding

import dwave_networkx as dnx
from dwave.system.samplers import DWaveSampler

n = 8

h = {}
J = {}
for i in range(n):
    h[i] = 0.0
    for j in range(i+1,n):
        J[(i,j)] = - 0.5

print(J)

bqm = BinaryQuadraticModel.from_ising(h, j)


def clique_embedding(bqm: BinaryQuadraticModel):
    qpu_sampler = DWaveSampler()
    shape = qpu_sampler.properties['topology']['shape']
    G = dnx.pegasus_graph(shape[0], node_list=qpu_sampler.nodelist, edge_list=qpu_sampler.edgelist)
    embedding = find_clique_embedding(bqm.variables, G, use_cache=True)
    print(embedding)
    return embedding

clique_embedding(bqm)
```

**Expected behavior**
find_clique_embedding may not return, or may terminate with an EOFError such as
```
  File "minorminer/busclique.pyx", line 93, in minorminer.busclique.find_clique_embedding
  File "minorminer/busclique.pyx", line 286, in minorminer.busclique.busgraph_cache.find_clique_embedding
  File "minorminer/busclique.pyx", line 130, in minorminer.busclique.busgraph_cache._ensure_clique_cache
  File "minorminer/busclique.pyx", line 210, in minorminer.busclique.busgraph_cache._fetch_cache
  File "minorminer/busclique.pyx", line 212, in minorminer.busclique.busgraph_cache._fetch_cache
  File "minorminer/busclique.pyx", line 215, in minorminer.busclique.busgraph_cache._fetch_cache
  File "minorminer/busclique.pyx", line 216, in minorminer.busclique.busgraph_cache._fetch_cache
EOFError: Ran out of input
```

**Workaround**
Use the above `clique_embedding` function or similar using `use_cache=False` instead of DWaveCliqueSampler. This prints a correct embedding that can be used directly with `FixedEmbeddingComposite`
```
{(0, 1): -0.5, (0, 2): -0.5, (0, 3): -0.5, (0, 4): -0.5, (0, 5): -0.5, (0, 6): -0.5, (0, 7): -0.5, (1, 2): -0.5, (1, 3): -0.5, (1, 4): -0.5, (1, 5): -0.5, (1, 6): -0.5, (1, 7): -0.5, (2, 3): -0.5, (2, 4): -0.5, (2, 5): -0.5, (2, 6): -0.5, (2, 7): -0.5, (3, 4): -0.5, (3, 5): -0.5, (3, 6): -0.5, (3, 7): -0.5, (4, 5): -0.5, (4, 6): -0.5, (4, 7): -0.5, (5, 6): -0.5, (5, 7): -0.5, (6, 7): -0.5}
{0: [180, 2940], 1: [195, 2955], 2: [150, 2970], 3: [165, 2985], 4: [210, 3000], 5: [225, 3015], 6: [240, 3030], 7: [255, 3045]}

```
**Environment:**
 - OS: [macOS Catalina 10.15.6]
 - Python version: 3.8
 - minorminer: 0.2.3
 - dwave-system: 1.1.1

**Comment by boothby** [comment]
Thanks for your bug report.  It's known that `find_clique_embedding` can take a couple of minutes the first time that it runs on your system (per sampler).  I wonder if you stopped it at just the wrong time (e.g. if it was in the middle of writing the cache to disk).  Would you please run the following, then try your code again with `use_cache=True` and allow it to finish?

```python
from minorminer.busclique import busgraph_cache
busgraph_cache.clear_all_caches()
```

**Comment by hmunozb** [comment]
Thanks, the embedding works now. Sorry it looks like I just overlooked the busgraph_cache class.

**Comment by boothby** [comment]
To the contrary, no apologies necessary!  The caching code should be more resilient, and I think I know how to prevent this in the future.  Thank you very much!
