### ISSUE TITLE
Old Cython version in Python install instructions

### ISSUE THREAD

**Issue by JoelPasvolsky** [dwavesystems/minorminer#165]
**Description**
README.rst says:
To install from this repository, run the setuptools script.
```
pip install cython==0.27
python setup.py install
```
But that gives the user an error:
```
$ pip install cython==0.27
Looking in indexes: https://pypi.org/simple, https://packagecloud.io/github/git-lfs/pypi/simple
Collecting cython==0.27

...

from .Visitor import VisitorTransform
      File "/tmp/pip-install-6458dk7f/cython/Cython/Compiler/Visitor.py", line 15, in <module>
        from . import ExprNodes
      File "/tmp/pip-install-6458dk7f/cython/Cython/Compiler/ExprNodes.py", line 2876
        await = None
              ^
    SyntaxError: invalid syntax
```

**To Reproduce**
Clone minorminer and try
```
pip install cython==0.27
```

**Expected behavior**
No errors following install instruction.

**Environment:**
 - OS: Ubuntu 16.0
 - Python version: 3.7

**Comment by randomir** [comment]
The reason seems to be version [0.27 doesn't ship binary wheels for py37+](https://pypi.org/project/Cython/0.27/#files).
