### ISSUE TITLE
FixedEmbeddingComposite crashes

### ISSUE THREAD

**Issue by DevelopDaily** [dwavesystems/minorminer#171]
Here is a simple test case to crash the function `FixedEmbeddingComposite`. The QUBO info is in this file 
[q96.zip](https://github.com/dwavesystems/minorminer/files/5587905/q96.zip), which is used to construct a 96x96 QUBO `numpy `matrix.

```
// Q comes from the attached file
model = dimod.BinaryQuadraticModel.from_numpy_matrix(Q)
sampler = DWaveSampler(solver={'qpu': True})  
found = find_embedding(model.quadratic, sampler.edgelist, verbose=1)

//The following line crashes.
sampler_fixed_embedding = FixedEmbeddingComposite(sampler, found)
```

The strange thing is that the `find_embedding `actually succeeds, but the `FixedEmbeddingComposite `crashes with this error:

`ValueError: no embedding found`

**Comment by joelgdwave** [comment]
Hello @DevelopDaily, I am not finding an embedding for this Q matrix, using ```find_embedding```. Could you please capture the embedding that you found, as a JSON object, and attach it here? ```find_embedding```, for me, is returning an empty set, indicating that it didn't find an embedding.

**Comment by arcondello** [comment]
`find_embedding` returns an empty dictionary when it cannot find an embedding. `FixedEmbeddingComposite` then raises an exception to indicate that to the user.

When you say that "`find_embedding` actually succeeds" do you mean that it returns an embedding or an empty dict?

**Comment by DevelopDaily** [comment]
The `find_embedding` returns an empty dictionary. I expect the `find_embedding `would also throw an exception if it cannot find an embedding as the `FixedEmbeddingComposite `does. Anyway, that is my wrong assumption.

Now that I understand the empty dictionary return actually means "failed to find an embedding", what should I do to make it find one?

Mind you, my QUBO matrix is quite simple. It is populated with random numbers between -10 and 10.

**Comment by arcondello** [comment]
First you should make sure that you're targeting an advantage system rather than a QPU.
```
sampler = DWaveSampler(solver=dict(topology__type='pegasus'))
```

If your QUBO is dense, you should try to use [DWaveCliqueSampler](https://docs.ocean.dwavesys.com/projects/system/en/stable/reference/samplers.html#dwavecliquesampler) with an advantage system. I believe 96 variables should fit.
```
sampler = DWaveCliqueSampler(solver=dict(topology__type='pegasus'))
```

An alternative would be to tune the running of minorminer, to see if a longer run will result in it finding an embedding.

**Comment by boothby** [comment]
An intermediate solution is to use the clique embedder (this is done under the hood with DWaveCliqueSampler)

```python
from minorminer.busclique import find_clique_embedding
sampler_graph = sampler.to_networkx_graph()
found = find_clique_embedding(96, sampler_graph)
```

**Comment by randomir** [comment]
Good suggestion, @arcondello. Just a minor typo, it should say `topology__type='pegasus'`.

**Comment by arcondello** [comment]
Thank's @randomir, fixed above.

**Comment by DevelopDaily** [comment]
@arcondello Thanks. Your advice works perfectly.

@boothby Your code does not work for me. Could you please elaborate more on your code? When running it, I got these arcane errors:


```
File "minorminer/busclique.pyx", line 85, in minorminer.busclique.find_clique_embedding

AttributeError: 'int' object has no attribute 'graph'
```


```
File "minorminer/busclique.pyx", line 90, in minorminer.busclique.find_clique_embedding

ValueError: g must be either a dwave_networkx.chimera_graph or a dwave_networkx.pegasus_graph

```

**Comment by boothby** [comment]
Ah, my apologies, I swapped the arguments to `find_clique_embedding`.  I've edited my comment.

**Comment by DevelopDaily** [comment]
@boothby Thanks. It works beautifully now.
