### ISSUE TITLE
Release macOS 10.9 wheels instead of 10.15?

### ISSUE THREAD

**Issue by randomir** [dwavesystems/minorminer#184]
Can we release 10.9, to support older macOSes?

More details in https://github.com/dwavesystems/dwave-neal/pull/71. In the meantime, [`wheel>0.34`](https://wheel.readthedocs.io/en/stable/news.html) says it has:
> Added automatic platform tag detection for macOS binary wheels

I've tested this auto-detection and it seems it produces 10.9 wheels on our other packages (e.g. greedy), but not for minorminer. Might be we actually use something that requires 10.15?

**Comment by boothby** [comment]
I didn't set up builds for macOS and I don't use that platform myself.  I don't do anything terribly exotic on the OS side of things, I don't see why 10.15 would specifically be required.

**Comment by randomir** [comment]
Obsoleted by switch to `cibuildwheel`.
