### ISSUE TITLE
Add support to release linux aarch64 wheels

### ISSUE THREAD

**Issue by odidev** [dwavesystems/minorminer#197]
On aarch64, `pip install minorminer` builds the wheels from source code and then installs it. I can see that the job to build Linux aarch64 wheel is added in the config.yml file. May I know the plan for releasing Linux AArch64 wheels on PyPI.

**Comment by arcondello** [comment]
Hi @odidev , just released [0.2.7.post0](https://github.com/dwavesystems/minorminer/releases/tag/0.2.7.post0).
