### ISSUE TITLE
Inconsistent `find_clique_embedding` API

### ISSUE THREAD

**Issue by randomir** [dwavesystems/minorminer#200]
`chimera.find_clique_embedding` accepts `target_edges`, while `pegasus.find_clique_embedding` accepts `target_graph`:

https://github.com/dwavesystems/minorminer/blob/ff4935d5fd7c70e64c2532adb0172f48b15078d6/minorminer/utils/chimera.py#L35

https://github.com/dwavesystems/minorminer/blob/ff4935d5fd7c70e64c2532adb0172f48b15078d6/minorminer/utils/pegasus.py#L73

The difference is directly propagated in `dwave.embedding.chimera`/`dwave.embedding.pegasus`, ultimately making embedding finding topology-specific (see [`hybrid.SubproblemCliqueEmbedder`](https://github.com/dwavesystems/dwave-hybrid/blob/e9aeb7fc59fb03ec5c1704a57258eeea053e3b82/hybrid/samplers.py#L163-L164) and [this bug](https://github.com/dwavesystems/dwave-hybrid/issues/264)).

**Comment by boothby** [comment]
The fix is to deprecate `dwave.embedding.chimera.find_embedding` and `dwave.embedding.pegasus.find_embedding`, in favor of `minorminer.busclique.find_embedding`.  I'd strongly suggest migrating to `busclique` immediately, as `pegasus.find_embedding` is horribly slow.

**Comment by boothby** [comment]
Blech, my grand deprecation plans have been dashed.  I've updated `chimera.find_embedding` to accept `m=None, target_graph=(not None)`.
