### ISSUE TITLE
matlab version is still broken in 2.7

### ISSUE THREAD

**Issue by navidaadit** [dwavesystems/minorminer#203]
The matlab version of minor miner is still broken.

**Comment by boothby** [comment]
Please don't make duplicate tickets

**Comment by navidaadit** [comment]
Ok I understand, thanks. But how is the current situation? Is there any
possibility that the matlab version will be fixed in 2.7? I have been using
1.8 so far which works fine.

Thanks.

**Comment by boothby** [comment]
No, 2.7 is released.  Please limit conversation about this issue to the open PR.
