### ISSUE TITLE
(Question) Is it ok to expect the same functionality on the provided python and C++ implementations?

### ISSUE THREAD

**Issue by almosnow** [dwavesystems/minorminer#219]
Hi all,

I like minorminer but prefer C++, I see that you provide a header library for it with a few examples,

My question is, if I use the C++ version of minorminer, do I get (almost) the same functionality as the python version, or is it like second-class to the latter?

Thanks.

**Comment by boothby** [comment]
The Python version is a wrapper over the C++ version, so their features are at near-parity.  There are a few differences
1. the `suspend_chains` parameter present in the Python wrapper is not implemented in the C++ interface
2. in Python, you can use arbitrary hashable node labels and a popular graph class (NetworkX), but in C++ the node labels must be integers that fill up an interval `[0, ..., n]`
3. in C++, you have a lot more control over the heuristic than is exposed in Python -- though much of this functionality can be accessed through the `miner` class.
4. Targeting C++ directly can improve runtime -- though, the overhead is a tiny fraction of the expected runtime of a problem I consider "normal" size

**Comment by almosnow** [comment]
Awesome, thanks!
