### ISSUE TITLE
Core dumped if problem graph is too small relative to target graph

### ISSUE THREAD

**Issue by tdgoodrich** [dwavesystems/minorminer#27]
Rerun the first example, but switch `triangle` and `square` when calling `find_embedding` (e.g. embed a square into a triangle). Output is:

```
munmap_chunk(): invalid pointer 
Aborted (core dumped)
```

I suspect the issue comes from the target graph having less vertices than the problem graph. If a Python exception could be thrown, that'd be great!

**Comment by boothby** [comment]
thanks Tim, I've been giving this the stink-eye; I'll sort it out in the coming week

**Comment by tdgoodrich** [comment]
No rush, not a pressing concern on my end. I'm happy to rerun my code that identified this issue if you want some fix verification, just let me know.

**Comment by boothby** [comment]
oh dang it's an embarrassing one-liner :roll_eyes:
