### ISSUE TITLE
find_embedding prints "failed during initialization. embeddings may be invalid."

### ISSUE THREAD

**Issue by tdgoodrich** [dwavesystems/minorminer#28]
Sometimes when `find_embedding` is called on inputs that are borderline un-embeddable, the following message is printed:

`failed during initialization. embeddings may be invalid.`

Consider raising an exception instead, so the code calling the function knows something is amiss. Otherwise, consider validating the returned embedding so that it is guaranteed to be valid.

**Comment by boothby** [comment]
addressed in #117
