### ISSUE TITLE
Fails to build when Boost / BoostGraph is present

### ISSUE THREAD

**Issue by amccaskey** [dwavesystems/minorminer#50]
See attached log file. 

Basically there is ambiguity between std::begin/std::end when integrating minorminer into another library where Boost/BoostGraph is present. Also, there is a clash between this libraries graph namespace and that from Boost. 

[make.txt](https://github.com/dwavesystems/minorminer/files/2177133/make.txt)

I have a fix in for this at https://github.com/amccaskey/minorminer. I will issue a pull request.

**Comment by boothby** [comment]
I've merged your pull request, thanks very much!
