### ISSUE TITLE
Python 3.7 user failed in compilation of minorminer extensions

### ISSUE THREAD

**Issue by sploiber** [dwavesystems/minorminer#52]
[Error code (07.18.2018).docx](https://github.com/dwavesystems/minorminer/files/2206242/Error.code.07.18.2018.docx)
On Windows 10, a user installed Python 3.7 and Pip, and then tried "pip install dwave-ocean-sdk".
An error (attached) occurred. It appears that there was an attempt to compile from source.
The user does not have Visual Studio C++.
The user did not attempt the compile. The user's only command was 'pip install dwave-ocean-sdk'.

**Comment by arcondello** [comment]
Hey sploiber,
We are behind on building wheels for python 3.7. I will add an issue to do that.
