### ISSUE TITLE
Debug/error messages printed on stdout/err

### ISSUE THREAD

**Issue by randomir** [dwavesystems/minorminer#62]
Python library errors are better raised as exceptions than printed to stdout/stderr. That way it's easier to actually handle them (or programmatically acknowledge them). For debug/error logging we could use the standard logging module.

To reproduce (one of many possible error messages):

```
>>> emb = minorminer.find_embedding({}, [])
never tried to embed anything; the qubit graph has no edges>>> 
```

Generalizes issue #28.

**Comment by boothby** [comment]
addressed in #117
