### ISSUE TITLE
"given bqm does not match the sampler's structure" on certain QUBOs/solver_limit

### ISSUE THREAD

**Issue by carlos-havier** [dwavesystems/minorminer#63]
**Description**
When embedding some QUBOs using minorminer, we get the mentioned error. By trial and error, increasing the value of solver_limit to 10000 prevents the error for appearing.

**To Reproduce**
Please download a MWE from https://megaupload.nz/meWbFdj2bb/minimal-qubo-model_zip and run solver_qbsolv.py changing use_minorminer=False to True in the last line. Other QUBOs saved in the data folder also have the same problem.

**Expected behavior**
Theoretically, the embedding should either fail or succeed. Instead, it succeeds but complaints about matching. Unexpectedly, the solver_limit parameter affects this behavior.

**Environment:**
 - OS: Ubuntu 18 LTS
 - Python version: 2.7

**Comment by arcondello** [comment]
Unfortunately we can't/shouldn't download files to run locally. Would you be able to create a [mcve](https://stackoverflow.com/help/mcve) to post here?

**Comment by carlos-havier** [comment]
Surething. I'm a bit busy these days but will craft and post one in the next 4 days or so. I'll hard-code the QUBO data in it.

Enviado desde Yahoo Mail con Android 
 
  El mié., oct. 24, 2018 a 12:03, Alexander Condello<notifications@github.com> escribió:   
Unfortunately we can't/shouldn't download files to run locally. Would you be able to create a mcve to post here?

**Comment by boothby** [comment]
This has been open for a year without update; please submit a proper mcve or I'll close this ticket.

**Comment by carlos-havier** [comment]
Hi,
Please allow me a week to go back to that code version and create an mcve.
I'll also need to regain access, since my user was locked out. Would it be possible for you to give me login credentials?
Thanks much,
Carlos

Enviado desde Yahoo Mail con Android 
 
  El jue., oct. 31, 2019 a 19:09, Kelly Boothby<notifications@github.com> escribió:   
This has been open for a year without update; please submit a proper mcve or I'll close this ticket.

**Comment by boothby** [comment]
Hi Carlos,

I'm not sure how you were accessing the system.  I'm told that if you have a leap account and you haven't linked it to your github account, you're eligible for additional time.  If this doesn't help, please email me at boothby@dwavesys.com and I'll try and sort something out internally.

Thanks!
