### ISSUE TITLE
RuntimeError on trivial (single-variable) BQMs

### ISSUE THREAD

**Issue by randomir** [dwavesystems/minorminer#66]
**Description**
`find_embedding` fails for single-variable problems / cycles in source edgelist.

**To Reproduce**
```
>>> import dimod
>>> from dwave.system.samplers import DWaveSampler
>>> from dwave.system.composites import EmbeddingComposite
...
>>> bqm = dimod.BinaryQuadraticModel({'a': 1}, {}, 0, dimod.SPIN)
>>> EmbeddingComposite(DWaveSampler()).sample(bqm)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/radomir/work/dwave-hybrid/env/lib/python3.5/site-packages/dwave/system/composites/embedding.py", line 219, in sample
    embedding = minorminer.find_embedding(source_edgelist, target_edgelist)
  File "python/minorminer.pyx", line 196, in minorminer.find_embedding
RuntimeError: Unknown exception
```

**Additional context**
For the failed BQM above, `source_edgelist == [('a', 'a')]` and `target_edgelist` is the standard chimera.

**Comment by chaowu2009** [comment]
I got the similar error too.  The "Unknown exception" really bothers people because I have no clue what is the problem there.

**Comment by boothby** [comment]
Dr. Wu, are you using a recent version of minorminer?  To my knowledge the "unknown exception" issue has been resolved -- if that's happening in the latest version, please open a new issue and include inputs that cause the problem.

**Comment by chaowu2009** [comment]
boothby, thanks for the reply. You are right. My minorminer was not updated to the latest version.  I hope in the answer section you can provide a description how the problem was solved. That will save people a lot of time. For example: the problem was addressed by updating minorminer to the latest version 0.1.8. Thanks.
