### ISSUE TITLE
PyPI upload fails for duplicate archives

### ISSUE THREAD

**Issue by randomir** [dwavesystems/minorminer#68]
Second attempt to upload sdist will fail (either from osx or manylinux deploy job), marking the complete build are failed. For an example, see: https://circleci.com/gh/dwavesystems/minorminer/593.

**Comment by arcondello** [comment]
Closed in https://github.com/dwavesystems/minorminer/commit/e713d3af61aacdab5089d51f93c9bbc84a2c8de2
