### ISSUE TITLE
Embedding a c6 chimera graph results in empty embedding being returned

### ISSUE THREAD

**Issue by davage** [dwavesystems/minorminer#70]
**Description**
Usually if the embedding doesn't fit on the QPU, an error is returned.

**To Reproduce**
Running the following code returns an empty embedding with no error:

```
import dwave_networkx as dnx
import minorminer as mm

graph = dnx.chimera_graph(m=6, n=6, t=4)
chimera_graph = dnx.chimera_graph(16)
graph_edges = graph.edges()

emb = mm.find_embedding(graph_edges, list(chimera_graph.edges()))
```

**Expected behavior**
I am not exactly sure how this should behave, but presumably the input ends up being too large to be embedded on the provided adjacency.

I was able to get an embedding back quick which I used m=6 and n=5 as in the following:

```
import dwave_networkx as dnx
import minorminer as mm

graph = dnx.chimera_graph(m=6, n=5, t=4)
chimera_graph = dnx.chimera_graph(16)
graph_edges = graph.edges()

emb = mm.find_embedding(graph_edges, list(chimera_graph.edges()))
```

**Environment:**
 - OS: Windows 10 Pro
 - Python version: 3.7.1

**Additional context**
This came up as a problem a community user was facing.

**Comment by boothby** [comment]
This is the documented signature of `minorminer.find_embedding`; not a bug.  Moreover, I don't think `minorminer` is the right tool for this particular task; do you just need a coordinate transformation?

It's easier to work with Chimera graphs of different sizes by using coordinate-based node labels

```
import dwave_networkx as dnx

graph = dnx.chimera_graph(m=6, n=6, t=4, coordinates=True)
coords = dnx.chimera.chimera_coordinates(16)
emb = {v: [coords.int(v)] for v in graph.nodes()}
```

otherwise,

```
graph = dnx.chimera_graph(m=6, n=6, t=4)
coords_in = dnx.chimera.chimera_coordinates(m=6, n=5, t=4)
coords_out = dnx.chimera.chimera_coordinates(16)
emb = {v: [coords_out.int(coords_in.tuple(v))] for v in graph.nodes()}
```

**Comment by boothby** [comment]
My mistake; this is in fact a documentation bug; that behavior is not clearly documented.
